name: Feature Request
description: Suggest an idea or improvement.
labels: [enhancement]
title: "feat: "
body:
  - type: textarea
    id: summary
    attributes:
      label: Proposal
      description: What would you like to see happen?
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this change valuable? How does it reduce energy usage or improve operability?
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Suggested implementation
  - type: input
    id: impact
    attributes:
      label: Expected impact metric
      placeholder: e.g., reduce joules/request by 5%
  - type: textarea
    id: extra
    attributes:
      label: Additional context
